# Generated by Django 5.2 on 2025-04-18 10:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the exercise (e.g., Bench Press)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of exercise', null=True)),
                ('body_part', models.CharField(choices=[('CH', 'Chest'), ('BK', 'Back'), ('LG', 'Legs'), ('SH', 'Shoulders'), ('AR', 'Arms'), ('CO', 'Core'), ('FB', 'Full Body'), ('OT', 'Other')], default='OT', help_text='Body part targeted', max_length=2)),
                ('owner', models.ForeignKey(blank=True, help_text='User who created the exercise', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date for the workout')),
                ('name', models.CharField(blank=True, help_text='Optional name for the workout (e.g., Monday Chest Day)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the workout session', null=True)),
                ('user', models.ForeignKey(help_text='The use who performed the workout', on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
