# Generated by Django 5.2 on 2025-04-18 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField(help_text='Number of repetitions performed')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight used for the set (e.g., in kg or lbs)', max_digits=6)),
                ('notes', models.TextField(blank=True, help_text='Optional notes specific to this set', null=True)),
                ('exercise', models.ForeignKey(help_text='The exercise performed in this set', on_delete=django.db.models.deletion.PROTECT, related_name='sets_performed', to='lb.exercise')),
                ('workout', models.ForeignKey(help_text='The workout session this set belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='lb.workout')),
            ],
            options={
                'ordering': ['workout', 'id'],
            },
        ),
    ]
