# Generated by Django 5.2 on 2025-11-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0002_workoutset'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='total_weight_lifted',
            field=models.IntegerField(default=0, help_text='Total weight lifted in the workout'),
        ),
    ]
