# Generated by Django 5.2 on 2025-11-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0003_fitbittoken'),
        ('lb', '0003_workout_total_weight_lifted'),
    ]

    operations = [
    ]
