# Generated by Django 5.2 on 2025-12-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0004_merge_20251129_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(blank=True, help_text='Exercises planned for this workout', related_name='planned_workouts', to='lb.exercise'),
        ),
    ]
