# Generated by Django 5.2 on 2025-12-04 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0005_workout_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date for the workout'),
        ),
    ]
