# Generated by Django 5.2 on 2026-01-18 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lb", "0006_alter_workout_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date for the metrics")),
                (
                    "resting_heart_rate",
                    models.PositiveIntegerField(
                        blank=True, help_text="Resting heart rate (bpm)", null=True
                    ),
                ),
                (
                    "hrv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Heart rate variability (RMSSD ms)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When data was last fetched"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Metrics",
                "verbose_name_plural": "User Metrics",
                "db_table": "lb_user_metrics",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
