# Generated by Django 5.2 on 2026-01-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0007_add_user_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Identifies if this is a reusable workout template'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='expected_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target weight/value (e.g. 80.0 for 80%, 8.0 for RPE 8, or exact kg)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='weight_mode',
            field=models.CharField(choices=[('EX', 'Exact Weight'), ('PC', 'Percentage of 1RM'), ('RP', 'Rate of Perceived Exertion')], default='EX', help_text='Mode for interpreting the weight/expected_weight', max_length=2),
        ),
    ]
